### ISSUE TITLE
Add support for bad ssh servers

### ISSUE THREAD

**Issue by Ekstazi** [amphp/ssh#4]
https://github.com/amphp/ssh/blob/a03e8da978273c221419ff465f05175aecd1877f/src/functions.php#L36

Some versions of openssh server doesn't proper terminate version string(RFC says that CR LF must be used). It uses LF instead of CR LF. Need to add support for such cases.

**Comment by kelunik** [comment]
Do you know which versions are affected?

**Comment by Ekstazi** [comment]
From https://www.openssh.com/releasenotes.html


Changes since OpenSSH 7.4
=========================
Fix various fallout and sharp edges caused by removing SSH protocol 1 support from the server, including the server banner string being incorrectly terminated with only \n (instead of \r\n), confusing
error messages from ssh-keyscan bz#2583 and a segfault in sshd 
if protocol v.1 was enabled for the client and sshd_config contained references to legacy keys bz#2686.

**Comment by kelunik** [comment]
Thanks, so the first fixed version is OpenSSH 7.5/7.5p1 (2017-03-20), which is more recent than I expected. I guess it's fine to fix then. Do you want to send a PR?

**Comment by Ekstazi** [comment]
yes. I'll do it.

**Comment by kelunik** [comment]
Thanks! I've fixed the comment and pushed another commit avoiding an infinite loop if the connection breaks during the read.
